version: "3.9"

services:
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ml_streamlit_app
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - .:/app